name: Test workflow to merge a branch to master
on: workflow_dispatch
jobs:
  merge_branch:
    name: "Demo to merge master to next(fast forward)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          ref: master

      - name: Merge Fast Forward
        uses: MaximeHeckel/github-action-merge-fast-forward@v1.1.0
        with:
          # Branch to merge
          branchtomerge: master
          # Branch that will be updated
          branch: next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
